//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkConnectionsTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetworkConnectionsTests.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YU1LX2J2TTtQV25TRUlvSDhOQF82NHp4Z1NwRjM9NFBtcWE0cyFYTDpLRHJfT0BxSmJBVTFreGEzR2MyQHQ4RT1qcUM4czs2WDIydmxSVEBvWW5kTTFQOVE5R0QxZW1GV09hb0UwMnlrWFU/eUhINndLTW5hS2FhIVNTSGRSZlFOUHNtPWJ6cEBKQE1KWVJnQjRfU2I9OGpmdkpVUUxFX2dhQUQwQV9oLQ==​.
        /// </summary>
        internal static string apiKey {
            get {
                return ResourceManager.GetString("apiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;access_token&quot;:&quot;305a80d7-aa8c-47f9-8ff5-8160e7e4f0b4&quot;,&quot;token_type&quot;:&quot;bearer&quot;,&quot;refresh_token&quot;:&quot;ac6dc334-834f-4936-a31a-5f1a10d21ca5&quot;,&quot;expires_in&quot;:75635,&quot;scope&quot;:&quot;read write&quot;}.
        /// </summary>
        internal static string AuthenticateNetworkObjTestAccessGranted {
            get {
                return ResourceManager.GetString("AuthenticateNetworkObjTestAccessGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;title&gt;JBoss Web/7.2.0.Final - JBWEB000064: Error report&lt;/title&gt;&lt;style&gt;&lt;!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuthenticateNetworkObjTestMissingCharacterFromUser {
            get {
                return ResourceManager.GetString("AuthenticateNetworkObjTestMissingCharacterFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;data&quot;:[{&quot;name&quot;:&quot;OSM&quot;,&quot;count&quot;:4265206},{&quot;name&quot;:&quot;Historical Twitter Reprocess&quot;,&quot;count&quot;:2851962},{&quot;name&quot;:&quot;Gnip - Twitter&quot;,&quot;count&quot;:1041475},{&quot;name&quot;:&quot;GDELT&quot;,&quot;count&quot;:636044},{&quot;name&quot;:&quot;Gazeteer&quot;,&quot;count&quot;:471464},{&quot;name&quot;:&quot;Flickr - Gnip&quot;,&quot;count&quot;:10555},{&quot;name&quot;:&quot;Anthrometer&quot;,&quot;count&quot;:869},{&quot;name&quot;:&quot;VK - Gnip&quot;,&quot;count&quot;:5}],&quot;shards&quot;:1555}.
        /// </summary>
        internal static string GetRequestNormalResponse {
            get {
                return ResourceManager.GetString("GetRequestNormalResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {      &quot;searchAreaWkt&quot;:&quot;POLYGON((-105 38, -105 39, -104 39, -104 38, -105 38))&quot;,    &quot;startDate&quot;:&quot;2014-01-01T00:00:00.000Z&quot;,    &quot;endDate&quot;:&quot;2015-04-30T23:59:59.999Z&quot;,    &quot;filters&quot;:[      ],    &quot;tagResults&quot;:false,    &quot;types&quot;:[          &quot;LandsatAcquisition&quot;, &quot;Acquisition&quot;    ]}.
        /// </summary>
        internal static string postString {
            get {
                return ResourceManager.GetString("postString", resourceCulture);
            }
        }
    }
}
