//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GbdxSettings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GbdxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GbdxResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GbdxSettings.GbdxResources", typeof(GbdxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be aware that all uploaded data is available to the public.  
        ///Private data should NOT be uploaded..
        /// </summary>
        public static string dataUploadWarning {
            get {
                return ResourceManager.GetString("dataUploadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download All Below 100,000.
        /// </summary>
        public static string Download_all_Below_100000 {
            get {
                return ResourceManager.GetString("Download_all_Below_100000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap emptyStar {
            get {
                object obj = ResourceManager.GetObject("emptyStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search terms and select area.
        /// </summary>
        public static string EnterSearchTerms {
            get {
                return ResourceManager.GetString("EnterSearchTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred with saving the password.  Please try again..
        /// </summary>
        public static string ErrorSavingPassword {
            get {
                return ResourceManager.GetString("ErrorSavingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap filledStar {
            get {
                object obj = ResourceManager.GetObject("filledStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Advanced Options.
        /// </summary>
        public static string Hide_Advanced_Options {
            get {
                return ResourceManager.GetString("Hide_Advanced_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounding box invalid. Please re-draw..
        /// </summary>
        public static string invalidBoundingBox {
            get {
                return ResourceManager.GetString("invalidBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date/time choosen.  Please choose again..
        /// </summary>
        public static string invalidDateTime {
            get {
                return ResourceManager.GetString("invalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url or api key is incorrect..
        /// </summary>
        public static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid username.
        ///Only letters and the &apos;.&apos; are allowed..
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username/Password.
        /// </summary>
        public static string InvalidUserPass {
            get {
                return ResourceManager.GetString("InvalidUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLTC stands for &quot;More Like This[ese] Cell[s].&quot;
        ///This tool shows a similarity heatmap based on a selection. Similar in nature to a &quot;More Like This &quot; function. If many cells are selected then there will either be an output layer for each selected cell, or the average will be calculated.  If an average is selected, then a graph of similarities between each feature will be printed out.
        ///
        ///1) Make a selection
        ///2) Choose the layer with the selection
        ///3) Click generate button.
        /// </summary>
        public static string mltcAbout {
            get {
                return ResourceManager.GetString("mltcAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Aggregation has been selected.  Please select a aggregation and try again..
        /// </summary>
        public static string noAggregationSelected {
            get {
                return ResourceManager.GetString("noAggregationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found..
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No features were selected.
        ///Please select features and try again..
        /// </summary>
        public static string noFeaturesSelected {
            get {
                return ResourceManager.GetString("noFeaturesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with password.  Please check the username and password settings..
        /// </summary>
        public static string PasswordProblemCheckSettings {
            get {
                return ResourceManager.GetString("PasswordProblemCheckSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose detail granularity.
        /// </summary>
        public static string pleaseChooseDetailsGranularity {
            get {
                return ResourceManager.GetString("pleaseChooseDetailsGranularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PleaseStandBy {
            get {
                object obj = ResourceManager.GetObject("PleaseStandBy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem decrypting password.  Please re-enter your password and try again..
        /// </summary>
        public static string problemDecryptingPassword {
            get {
                return ResourceManager.GetString("problemDecryptingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem during delete operation.  Please try again.
        /// </summary>
        public static string ProblemWithDelete {
            get {
                return ResourceManager.GetString("ProblemWithDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the password.  Please set the password and try again..
        /// </summary>
        public static string ProblemWithPasswordReSet {
            get {
                return ResourceManager.GetString("ProblemWithPasswordReSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        public static string Queued {
            get {
                return ResourceManager.GetString("Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBDX Layer already exists.  If you want to re-add the layer to ArcMap please remove the layer and click this button again..
        /// </summary>
        public static string Raster_DoesWmsLayerExist_Layer_already_exists___If_you_want_to_re_add_the_layer_to_ArcMap_please_remove_the_layer_and_click_this_button_again_ {
            get {
                return ResourceManager.GetString("Raster_DoesWmsLayerExist_Layer_already_exists___If_you_want_to_re_add_the_layer_t" +
                        "o_ArcMap_please_remove_the_layer_and_click_this_button_again_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click Select Area and redraw bounding box by clicking and dragging to create a polygon..
        /// </summary>
        public static string redrawBoundingBox {
            get {
                return ResourceManager.GetString("redrawBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching.
        /// </summary>
        public static string SearchingText {
            get {
                return ResourceManager.GetString("SearchingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Items:.
        /// </summary>
        public static string selectedItems {
            get {
                return ResourceManager.GetString("selectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Advanced Options.
        /// </summary>
        public static string Show_Advanced_Options {
            get {
                return ResourceManager.GetString("Show_Advanced_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled.  
        ///The file size is greater than 100 MB..
        /// </summary>
        public static string sizeToBig100 {
            get {
                return ResourceManager.GetString("sizeToBig100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again..
        /// </summary>
        public static string Source_ErrorMessage {
            get {
                return ResourceManager.GetString("Source_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Connection..
        /// </summary>
        public static string SuccessfulConnection {
            get {
                return ResourceManager.GetString("SuccessfulConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Items: .
        /// </summary>
        public static string totalItems {
            get {
                return ResourceManager.GetString("totalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to access this functionality, upgrade your account..
        /// </summary>
        public static string upgradeRequired {
            get {
                return ResourceManager.GetString("upgradeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to https://gbdx.geobigdata.io/account/login/ - Login &gt; User Settings &gt; API Key.
        /// </summary>
        public static string whereToGetApiKey {
            get {
                return ResourceManager.GetString("whereToGetApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Projection needs to be WGS 1984..
        /// </summary>
        public static string wrongSpatialReference {
            get {
                return ResourceManager.GetString("wrongSpatialReference", resourceCulture);
            }
        }
    }
}
