//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Answer_Factory_Unit_Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Answer_Factory_Unit_Tests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;id&quot;:&quot;dabd1296-dd7f-4c7a-8b14-d16b6a8a6106&quot;,&quot;owner&quot;:&quot;rwittmer&quot;,&quot;name&quot;:&quot;webapp create test&quot;,&quot;accountId&quot;:&quot;596bd3ed-ffad-496f-9394-291648fb8250&quot;,&quot;aois&quot;:[{&quot;type&quot;:&quot;Polygon&quot;,&quot;coordinates&quot;:[[[33.046863,44.425896],[33.046856,44.425899],[33.04685,44.425903],[33.046845,44.425908],[33.04684,44.425915],[33.046837,44.425921],[33.046835,44.425929],[32.805136,46.080846],[32.805136,46.080854],[32.805137,46.080861],[32.805139,46.080868],[32.805143,46.080875],[32.805148,46.080881],[32.805154,46.080886],[32.805161,46.080889] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Project2JsonData {
            get {
                return ResourceManager.GetString("Project2JsonData", resourceCulture);
            }
        }
    }
}
