//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoredQueriesTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoredQueriesTests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;name&quot;:&quot;AddedTest&quot;,&quot;date&quot;:&quot;2015-05-14T15:16:28.464Z&quot;,&quot;query&quot;:&quot;I am new here&quot;,&quot;timeline&quot;:{&quot;start&quot;:&quot;2015-01-01T00:00:00.000Z&quot;,&quot;end&quot;:&quot;2015-05-14T15:16:28.464Z&quot;},&quot;zoom&quot;:0,&quot;map&quot;:{&quot;bottom&quot;:0.0,&quot;left&quot;:0.0,&quot;top&quot;:0.0,&quot;right&quot;:0.0},&quot;polygon&quot;:null,&quot;properties&quot;:{&quot;EsriAddin&quot;:{&quot;QueryLimit&quot;:&quot;5000&quot;,&quot;DateLimit&quot;:&quot;Custom&quot;}}},{&quot;name&quot;:&quot;Default Workspace&quot;,&quot;date&quot;:&quot;2015-05-05T06:01:29.890Z&quot;,&quot;query&quot;:&quot;ebola&quot;,&quot;timeline&quot;:{&quot;start&quot;:&quot;2015-05-05T06:01:29.890Z&quot;,&quot;end&quot;:&quot;2015-05-05T06:01:29.890Z&quot;},&quot;zoom&quot;:4,&quot;map&quot;:{&quot;bottom&quot;:4.121736355332121,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OneItemAddedReturn {
            get {
                return ResourceManager.GetString("OneItemAddedReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;name&quot;:&quot;AddedTest&quot;,&quot;date&quot;:&quot;2015-05-14T15:16:28.464Z&quot;,&quot;query&quot;:&quot;I was new&quot;,&quot;timeline&quot;:{&quot;start&quot;:&quot;2015-01-01T00:00:00.000Z&quot;,&quot;end&quot;:&quot;2015-05-14T15:16:28.464Z&quot;},&quot;zoom&quot;:0,&quot;map&quot;:{&quot;bottom&quot;:0.0,&quot;left&quot;:0.0,&quot;top&quot;:0.0,&quot;right&quot;:0.0},&quot;polygon&quot;:null,&quot;properties&quot;:{&quot;EsriAddin&quot;:{&quot;QueryLimit&quot;:&quot;5000&quot;,&quot;DateLimit&quot;:&quot;Custom&quot;}}},{&quot;name&quot;:&quot;Default Workspace&quot;,&quot;date&quot;:&quot;2015-05-05T06:01:29.890Z&quot;,&quot;query&quot;:&quot;ebola&quot;,&quot;timeline&quot;:{&quot;start&quot;:&quot;2015-05-05T06:01:29.890Z&quot;,&quot;end&quot;:&quot;2015-05-05T06:01:29.890Z&quot;},&quot;zoom&quot;:4,&quot;map&quot;:{&quot;bottom&quot;:4.121736355332121,&quot;left [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OneItemUpdatedReturn {
            get {
                return ResourceManager.GetString("OneItemUpdatedReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;name&quot;:&quot;Default Workspace&quot;,&quot;date&quot;:&quot;2015-05-05T06:01:29.890Z&quot;,&quot;query&quot;:&quot;ebola&quot;,&quot;timeline&quot;:{&quot;start&quot;:&quot;2015-05-05T06:01:29.890Z&quot;,&quot;end&quot;:&quot;2015-05-05T06:01:29.890Z&quot;},&quot;zoom&quot;:4,&quot;map&quot;:{&quot;bottom&quot;:4.121736355332121,&quot;left&quot;:-65.38515957031312,&quot;top&quot;:58.99244532774582,&quot;right&quot;:75.23984042968688},&quot;polygon&quot;:[[{&quot;x&quot;:-97.03281427872767,&quot;y&quot;:36.13586357340484},{&quot;x&quot;:-97.03281427872767,&quot;y&quot;:36.13757475463792},{&quot;x&quot;:-97.0217445576513,&quot;y&quot;:36.13757475463792},{&quot;x&quot;:-97.0217445576513,&quot;y&quot;:36.13586357340484},{&quot;x&quot;:-97.03281427872767,&quot;y&quot;:36.135 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwoQueryReturned {
            get {
                return ResourceManager.GetString("TwoQueryReturned", resourceCulture);
            }
        }
    }
}
