//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBDTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GBDTests.TestResource", typeof(TestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;type&quot;:&quot;Feature&quot;,&quot;geometry&quot;:{&quot;type&quot;:&quot;MultiPolygon&quot;,&quot;coordinates&quot;:[[[[-90.4631238,38.7247225],[-90.21653602,38.75189523],[-90.21576338,38.63032904],[-90.46341164,38.6024272],[-90.4631238,38.7247225]]]]},&quot;properties&quot;:{&quot;ingest_source&quot;:&quot;GBDX_INGEST_ALPHA&quot;,&quot;access&quot;:{&quot;groups&quot;:[&quot;_ALL_&quot;],&quot;users&quot;:[&quot;_ALL_&quot;]},&quot;item_date&quot;:&quot;2017-06-07T19:52:40.527Z&quot;,&quot;original_crs&quot;:&quot;EPSG:4326&quot;,&quot;item_type&quot;:[&quot;GBDXCatalogRecord&quot;,&quot;IDAHOImage&quot;,&quot;DigitalGlobeProduct&quot;,&quot;WV01&quot;],&quot;format&quot;:null,&quot;ingest_date&quot;:&quot;2017-06-17T22:23:16.989Z&quot;,&quot;source&quot;:null, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CatalogResponseItem {
            get {
                return ResourceManager.GetString("CatalogResponseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;geometry&quot;:{&quot;type&quot;:&quot;MultiPolygon&quot;,&quot;coordinates&quot;:[[[[-90.4631238,38.7247225],[-90.21653602,38.75189523],[-90.21576338,38.63032904],[-90.46341164,38.6024272],[-90.4631238,38.7247225]]]]}}.
        /// </summary>
        internal static string geometry {
            get {
                return ResourceManager.GetString("geometry", resourceCulture);
            }
        }
    }
}
